-- Run if uploads fail (table missing)
-- https://supabase.com/dashboard/project/wkdcypzmvcqemslxdkqv/sql/new

create table if not exists documents (
  id bigint generated by default as identity primary key,
  name text not null,
  size text,
  status text default 'ready',
  label text,
  progress int,
  storage_path text,
  created_at timestamptz default now()
);

alter table documents enable row level security;
drop policy if exists "documents_anon_all" on documents;
create policy "documents_anon_all" on documents for all using (true) with check (true);
