-- Run in Supabase Dashboard → SQL Editor

create table if not exists lectures (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null,
  duration text,
  date date,
  date_label text,
  instructor text,
  instructor_initials text,
  thumb_class text default 'thumb-physics',
  created_at timestamptz default now()
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  name text not null,
  size text,
  status text default 'ready',
  label text,
  progress int,
  storage_path text,
  created_at timestamptz default now()
);

create table if not exists user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table lectures enable row level security;
alter table documents enable row level security;
alter table user_settings enable row level security;

-- Dev policies (tighten before production)
create policy "lectures_anon_all" on lectures for all using (true) with check (true);
create policy "documents_anon_all" on documents for all using (true) with check (true);
create policy "settings_anon_all" on user_settings for all using (true) with check (true);

insert into lectures (title, subject, duration, date, date_label, instructor, instructor_initials, thumb_class)
values
  ('Introduction to Quantum Physics', 'Physics', '45:20', '2023-10-24', 'Oct 24, 2023', 'Dr. Einstein AI', 'DE', 'thumb-physics'),
  ('Advanced React Hooks & Patterns', 'CS', '32:15', '2023-10-18', 'Oct 18, 2023', 'Prof. Code AI', 'PC', 'thumb-cs'),
  ('Linear Algebra Fundamentals', 'Math', '58:40', '2023-10-12', 'Oct 12, 2023', 'Dr. Matrix AI', 'DM', 'thumb-math')
on conflict do nothing;
